# Basic
title: Yirui (Ruby) Fang
subtitle: Personal Blog & Learnig Journal
description: You will know be better here :)
# 头像里面的标题
avatarTitle: Ruby
# 头像里面的描述
avatarDesc: Investment
url: "https://www.linkedin.com/in/yiruifang2026/"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Social
#social:
#    weibo: 5366874726 
#    github: leopardpan
#    # zhihu: panpanleopard
#    # juejin: xxx
#    jianshu: 2ada30d8d0f7
#    # twitter: 
#    mail: leopardpan@icloud.com


# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-84134159-3  
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 技术支持, description: support, url: '/support'}      
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


